komodo:
  # Add additonal vars: section for ssh keyfiles, etc.
  hosts:
    komodo1:
      ansible_host: 10.10.10.30
    komodo2:
      ansible_host: 10.10.10.31
    komodo3:
      ansible_host: 10.10.10.32
      connection: local
  children:
    komodo:
      vars:
        # These variables are only needed if using the server management feature
        # This feature allows the role to automatically register and update
        # servers in komodo core in addition to deploying periphery
        komodo_core_url: "http://10.10.10.30:9120"
        # Encrypt these with vault!
        komodo_core_api_key: "K-TodnQ41FWfGBqOc0LCcUkPAR4FEfPSwwBxnNquyM"
        komodo_core_api_secret: "S-eFdzn48GRUM6e4VYCHzdMzmVTw8f8bSbfBdHCTGB"
        # Default to allowing server management feature. Can be overriden
        enable_server_management: true
        komodo_passkeys:
          - mailabanthan123
      children:
        core:
          hosts:
            komodo1:
              periphery_port: 8199
              komodo_allowed_ips:
                - "10.10.10.30"
              server_address: https://host.docker.internal:{{ periphery_port }}
              komodo_bind_ip: "{{ ansible_docker0.ipv4.address}}"
        periphery:
          hosts:
            komodo2:
              generate_server_passkey: true
              komodo_allowed_ips:
                - "{{ hostvars['komodo_host1'].ansible_host }}"
                - 10.10.10.0/24
            komodo3:
              generate_server_passkey: true
              komodo_allowed_ips:
                - "{{ hostvars['komodo_host1'].ansible_host }}"
                - 10.10.10.0/24
