---
- name: Update package and config.  
  hosts: vm 
  gather_facts: no
  roles:
    - update_package
  become: true

- name: install docker
  hosts: vm 
  gather_facts: no
  roles:
    - docker
  become: true