destination_branches:
  - terraform
dirs:
  terraform:
    workspaces:
      d3-homelab:
hooks:
  all:
    pre:
      - type: run
        cmd: ['echo', 'Starting Terraform operation']
workflows:
  - tag_query: "production"
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=production.tfvars"]