#data "local_file" "ssh_public_key" {
#  filename = "./rsa.pub" 
#}

resource "proxmox_virtual_environment_file" "user_data_cloud_config" {
  content_type = "snippets"
  datastore_id = "cFS"
  node_name    = var.virtual_environment_nodeA_name

  source_raw {
    data = <<-EOF
    #cloud-config
    timezone: Asia/Singapore
    users:
      - name: d3
        groups:
          - sudo
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK6165evr8XFUam+k9c5W2A2Z/8kc/3zX2Lx2qS8Kx5FStKxKKVlmpGSrl3HmRSISqpfsQGQ2BCklNaO1kHwenmTgElEsCWhZiki3uhfCJ+zFnIsacRekCFvhvSi4rdQ53xRIusjt3kWkAKwvpbbEwE7yOyGOGkhD6WljxeG/nTRSKdbXAmv57RfZBgyZpsrEEW8P/9pJLDu4+UOu15ITJk/nMd43NK3/6JZfuE8Txfed1Eq6sr4NvTddy5NRaEQJYj6Lxfz8mDPyyYr0BvcUPUz/U5E2UHDn82z1J2LhLDBIaXyK0WgP1gQNnkLY4iET3MMnnV7PSwKTWCtpdPB5+7AP6KTU3fgk8hrFdWN45w1yssnnbd5hcRlND6Ou+aRxTQPe5jCCsP/5YRWNK0ms/3e+fYxo3iGpjoiUW+bsPGR0k6itgi3J5Qc4fKPxQ0iQs8inWMdTRamB/C2jQbBDTNu+/Nw+QbWQTY/cxAYKXsdde/BOKdY8786IJKGf/MqwA2Pn4yr0qQmQDSH67QTl8Emfv/fR6dEscInWCvlNMa+KmK1LiT/r+wteiQwoMfXxvZdgTZacQsLqIjOJ93FDnvxWVxtRxFSDfCleCIfEaz3F/+lojmvS2Zoc9OTNsZ6XRr2i6lP3LvTG3BoBdxzijQY1bJ01d+aOJVZzgH4aZKQ== Generated By Termius
        sudo: ALL=(ALL) NOPASSWD:ALL
    package_update: true
    packages:
      - qemu-guest-agent
      - net-tools
      - curl
    runcmd:
      - systemctl enable qemu-guest-agent
      - systemctl start qemu-guest-agent
      - echo "done" > /tmp/cloud-config.done
    EOF

    file_name = "user-data-cloud-config.yaml"
  }

}