name: omni-on-prem

services:
  omni:
    container_name: omni
    image: "ghcr.io/siderolabs/omni:${OMNI_IMG_TAG}"
    env_file:
      - .env
    devices:
      - /dev/net/tun
    volumes:
      - ./ca.pem:/etc/ssl/certs/ca-certificates.crt:ro
      - ./server-key.pem:/server-key.pem:ro
      - ./server-chain.pem:/server-chan.pem:ro
      - ./omni.asc:/omni.asc:ro
      - $HOME/sqlite:/_out/sqlite:rw
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    command: >
      --name=${NAME} \
      --cert=/server-chain.pem \
      --key=/server-key.pem \
      --machine-api-cert=/server-chain.pem \ 
      --machine-api-key=/server-key.pem \
      --machine-api-bind-addr=0.0.0.0:8090 \
      --private-key-source=file://omni.asc \
      --event-sink-port=8091 \
      --bind-addr=0.0.0.0:443 \
      --k8s-proxy-bind-addr=0.0.0.0:8100 \
      --advertised-api-url=https://${OMNI_ENDPOINT}/ \
      --machine-api-advertised-url=https://${OMNI_ENDPOINT}:8090/ \
      --siderolink-wireguard-advertised-addr=${HOST_PUBLIC_IP}:50180 \ 
      --advertised-kubernetes-proxy-url=https://${OMNI_ENDPOINT}:8100/ \ 
      --auth-auth0-enabled=false \
      --auth-oidc-enabled=true \
      --auth-oidc-provider-url=https://${AUTH_ENDPOINT}:5556 \
      --auth-oidc-client-id=omni \
      --auth-oidc-client-secret=omni-dex-secret \
      --auth-oidc-scopes=openid \
      --auth-oidc-scopes=profile \
      --auth-oidc-scopes=email \
      --sqlite-storage-path=/_out/sqlite/omni.db \
      --initial-users=${OMNI_USER_EMAIL}

  dex:
    container_name: dex
    image: ghcr.io/dexidp/dex:v2.41.1
    restart: unless-stopped
    user: "1002:1002"
    ports:
      - 5556:5556
    volumes:
      - ${PWD}/dex.yaml:/etc/dex/dex.yaml:ro
      - ${PWD}/server-key.pem:/etc/dex/tls/server-key.pem:ro
      - ${PWD}/server-chain.pem:/etc/dex/tls/server-chain.pem:ro
    command: dex serve /etc/dex/dex.yaml