- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - bc
      - curl
      - expect
      - git
      - ca-certificates
    state: present

- name: Create Docker GPG key directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add repo using key from URL
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    architectures: amd64
    suites: trixie 
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present
    enabled: true

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker and Docker Compose
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: d3
    groups: docker
    ppend: yes