---
    - name: EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present
      become: true
    - name: Ceph repository
      ansible.builtin.yum_repository:
        name: Ceph-noarch
        description: Ceph noarch
        file: ceph
        baseurl: https://download.proxmox.com/debian/ceph-squid
        gpgcheck: yes
        gpgkey: https://download.ceph.com/keys/release.gpg
        http://download.proxmox.com/debian/pve/dists/trixie/pve-no-subscription/binary-amd64/proxmox-archive-keyring_4.0_all.deb
    - name: Ceph repository $basearch
      ansible.builtin.yum_repository:
        name: Ceph
        description: Ceph $basearch
        file: ceph
        baseurl: https://download.ceph.com/rpm-quincy/el8/$basearch
        gpgcheck: yes
        gpgkey: https://download.ceph.com/keys/release.gpg
      become: true
#    - name: Install ceph
 #     ansible.builtin.dnf:
  #      name: ceph-common
   #     state: latest
    #  become: true
    - name: Download ceph config
      ansible.builtin.copy:
        src: '{{playbook_dir}}/ceph.conf'
        dest: /etc/ceph/ceph.conf
        owner: root
        group: root
        mode: '0664'
      become: true
    - name: Download ceph user key
      ansible.builtin.copy:
        src: '{{playbook_dir}}/ceph.client.kubedata.keyring'
        dest: /etc/ceph/ceph.client.kubedata.keyring
        owner: root
        group: root
        mode: '0664'
      become: true
    - name: update fstab
      ansible.posix.mount:
        fstype: ceph
        path: /mnt/cFS
        state: mounted
        src: komodo@.cFS=/
        opts: mon_addr=10.10.10.10:6789/10.10.10.15:6789/10.10.10.17:6789/10.10.10.18:6789/10.10.10.19:6789,rw,noatime,_netdev
      become: true